# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import EigenVector_pb2 as EigenVector__pb2

GRPC_GENERATED_VERSION = '1.65.5'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in EigenVector_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class EigenVectorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetEigenVector = channel.stream_stream(
                '/eigenvector.EigenVector/GetEigenVector',
                request_serializer=EigenVector__pb2.EigenVectorRequest.SerializeToString,
                response_deserializer=EigenVector__pb2.EigenVectorResponse.FromString,
                _registered_method=True)


class EigenVectorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetEigenVector(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EigenVectorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetEigenVector': grpc.stream_stream_rpc_method_handler(
                    servicer.GetEigenVector,
                    request_deserializer=EigenVector__pb2.EigenVectorRequest.FromString,
                    response_serializer=EigenVector__pb2.EigenVectorResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'eigenvector.EigenVector', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('eigenvector.EigenVector', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EigenVector(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetEigenVector(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/eigenvector.EigenVector/GetEigenVector',
            EigenVector__pb2.EigenVectorRequest.SerializeToString,
            EigenVector__pb2.EigenVectorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
