# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: NPime.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bNPime.proto\x12\x06nprime\"\x1e\n\x0cNPimeRequest\x12\x0e\n\x06number\x18\x01 \x01(\x05\"\x1e\n\rNPimeResponse\x12\r\n\x05prime\x18\x01 \x01(\x05\x32\x42\n\x05NPime\x12\x39\n\x08GetNPime\x12\x14.nprime.NPimeRequest\x1a\x15.nprime.NPimeResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'NPime_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NPIMEREQUEST']._serialized_start=23
  _globals['_NPIMEREQUEST']._serialized_end=53
  _globals['_NPIMERESPONSE']._serialized_start=55
  _globals['_NPIMERESPONSE']._serialized_end=85
  _globals['_NPIME']._serialized_start=87
  _globals['_NPIME']._serialized_end=153
# @@protoc_insertion_point(module_scope)
