// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: NPime.proto

package NPrime

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NPrime_GetNPrime_FullMethodName = "/NPrime/GetNPrime"
)

// NPrimeClient is the client API for NPrime service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NPrimeClient interface {
	GetNPrime(ctx context.Context, in *NPrimeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NPrimeResponse], error)
}

type nPrimeClient struct {
	cc grpc.ClientConnInterface
}

func NewNPrimeClient(cc grpc.ClientConnInterface) NPrimeClient {
	return &nPrimeClient{cc}
}

func (c *nPrimeClient) GetNPrime(ctx context.Context, in *NPrimeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NPrimeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NPrime_ServiceDesc.Streams[0], NPrime_GetNPrime_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[NPrimeRequest, NPrimeResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NPrime_GetNPrimeClient = grpc.ServerStreamingClient[NPrimeResponse]

// NPrimeServer is the server API for NPrime service.
// All implementations must embed UnimplementedNPrimeServer
// for forward compatibility.
type NPrimeServer interface {
	GetNPrime(*NPrimeRequest, grpc.ServerStreamingServer[NPrimeResponse]) error
	mustEmbedUnimplementedNPrimeServer()
}

// UnimplementedNPrimeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNPrimeServer struct{}

func (UnimplementedNPrimeServer) GetNPrime(*NPrimeRequest, grpc.ServerStreamingServer[NPrimeResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetNPrime not implemented")
}
func (UnimplementedNPrimeServer) mustEmbedUnimplementedNPrimeServer() {}
func (UnimplementedNPrimeServer) testEmbeddedByValue()                {}

// UnsafeNPrimeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NPrimeServer will
// result in compilation errors.
type UnsafeNPrimeServer interface {
	mustEmbedUnimplementedNPrimeServer()
}

func RegisterNPrimeServer(s grpc.ServiceRegistrar, srv NPrimeServer) {
	// If the following call pancis, it indicates UnimplementedNPrimeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NPrime_ServiceDesc, srv)
}

func _NPrime_GetNPrime_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(NPrimeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NPrimeServer).GetNPrime(m, &grpc.GenericServerStream[NPrimeRequest, NPrimeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NPrime_GetNPrimeServer = grpc.ServerStreamingServer[NPrimeResponse]

// NPrime_ServiceDesc is the grpc.ServiceDesc for NPrime service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NPrime_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "NPrime",
	HandlerType: (*NPrimeServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetNPrime",
			Handler:       _NPrime_GetNPrime_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "NPime.proto",
}
